// src/app/layout.js
import "./globals.css";
import Providers from "./components/Providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// src/app/layout.js  (server component)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
